import { defineConfig, globalIgnores } from 'eslint/config';
import cheminfo from 'eslint-config-cheminfo-typescript';

export default defineConfig(
  globalIgnores([
    'build/out',
    'coverage',
    'lib',
    // Generated by build/embed-wasm.js from the Emscripten output.
    'src/wasm/data.ts',
    'src/wasm/glue.ts',
  ]),
  cheminfo,
);
