// This file is generated by build/embed-wasm.js. Do not edit by hand.
// Run `npm run build-wasm` to regenerate it.

/** Version of the surge C program the embedded WebAssembly was compiled from. */
export const SURGE_VERSION = '2.0';

/** Version of the nauty library surge is built on. */
export const NAUTY_VERSION = '2.9.3';

/** Version of the Emscripten toolchain that compiled it. */
export const EMSCRIPTEN_VERSION = '6.0.6';
